{% set name = "asgiref" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d6c4a8a1c99f58eaa3bc392ee04e3587b693f09e3af1f3f16a09094f334eb52

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typing_extensions

test:
  imports:
    - asgiref

about:
  home: https://github.com/django/asgiref
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ASGI in-memory channel layer
  doc_url: https://asgi.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
    - carlodri
